name: e2e_mock_provider_tests

on:
  workflow_dispatch:
    inputs:
      registry:
        description: 'Registry for pulling images'
        required: true
        default: 'gcr.io/k8s-staging-csi-secrets-store'
      driverImageName:
        description: 'Secret Store CSI driver image name'
        required: true
        default: 'driver'
      crdImageName:
        description: 'Secret Store CSI driver CRD image name'
        required: true
        default: 'driver-crds'
      imageVersion:
        description: 'image version for Secret Store CSI driver and CRDs'
        required: true
        default: 'v1.CHANGE_ME'

permissions:
  contents: read

jobs:
  e2e-test:
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    strategy:
      matrix:
        KUBERNETES_VERSION: ["v1.30.10", "v1.31.6", "v1.32.3"]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c95a14d0e5bab51a9f56296a4eb0e416910cd350 # v2.10.3
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.0.0
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup BATS
        uses: mig4/setup-bats@af9a00deb21b5d795cabfeaa8d9060410377686d # v1.2.0
        with:
          bats-version: 1.4.1
      - name: Setup Kind
        uses: engineerd/setup-kind@aa272fe2a7309878ffc2a81c56cfe3ef108ae7d0 # v0.5.0
        with:
          version: "v0.27.0"
          image: "kindest/node:${{ matrix.KUBERNETES_VERSION }}"
      - name: Test
        run: |
          # GH action sets this var by default. We need to explicitly unset it so that build commit hash is not appended to image tag.
          unset CI

          make e2e-helm-deploy e2e-mock-provider-container e2e-provider-deploy e2e-provider
        env:
          REGISTRY: ${{ github.event.inputs.registry }}
          IMAGE_NAME: ${{ github.event.inputs.driverImageName }}
          CRD_IMAGE_NAME: ${{ github.event.inputs.crdImageName }}
          IMAGE_VERSION: ${{ github.event.inputs.imageVersion }}
